server:
  port: 8000
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/accessiongdatajpa?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: NoPassword4Mysql!
    driver-class-name: com.mysql.jdbc.Driver
  swagger2:
    enabled: true
# Swagger
swagger:
  host: localhost
  title: SpringBoot 整合 Swagger2
  description: jpa演示
  disabled: false # 是否禁用swagger
  redirect-uri: / # 禁用swagger时的重定向地址

#spring.jpa.hibernate.ddl-auto: update
#spring.datasource.url: jdbc:mysql://localhost:3306/accessiongdatajpa?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
#spring.datasource.username: root
#spring.datasource.password: NoPassword4Mysql!
#spring.datasource.driver-class-name: com.mysql.jdbc.Driver
